version: "3.8"

services:
  mongodb:
    container_name: mongo-service
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-network
    restart: unless-stopped

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - ecommerce-network
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    networks:
      - ecommerce-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  ecommerce-network:
    driver: bridge
